export const tables = [
  {
    tableNumber: 1,
    tableType: "squareBig",
    numberOfChairs: 8,
    status: "Available",
    x: 100,
    y: 50,
    tablePrice: 750,
  },
  {
    tableNumber: 2,
    tableType: "roundMedium",
    numberOfChairs: 2,
    status: "Available",
    x: 280,
    y: 50,
    tablePrice: 450,
  },
  {
    tableNumber: 3,
    tableType: "roundMedium",
    numberOfChairs: 10,
    status: "Seated",
    x: 420,
    y: 50,
    tablePrice: 450,
  },
  {
    tableNumber: 4,
    tableType: "roundMedium",
    numberOfChairs: 2,
    status: "Available",
    x: 560,
    y: 50,
    tablePrice: 450,
  },
  {
    tableNumber: 5,
    tableType: "roundMedium",
    numberOfChairs: 2,
    status: "Seated",
    x: 690,
    y: 50,
    tablePrice: 450,
  },
  {
    tableNumber: 6,
    tableType: "roundMedium",
    numberOfChairs: 10,
    status: "Available",
    x: 830,
    y: 50,
    tablePrice: 450,
  },
  {
    tableNumber: 7,
    tableType: "squareBig",
    numberOfChairs: 8,
    status: "Seated",
    x: 980,
    y: 50,
    tablePrice: 750,
  },
  {
    tableNumber: 8,
    tableType: "roundBig",
    numberOfChairs: 4,
    status: "Available",
    x: 100,
    y: 200,
    tablePrice: 500,
  },
  {
    tableNumber: 9,
    tableType: "roundBig",
    numberOfChairs: 4,
    status: "Available",
    x: 100,
    y: 350,
    tablePrice: 500,
  },
  {
    tableNumber: 10,
    tableType: "rectangle",
    numberOfChairs: 16,
    status: "Seated",
    x: 260,
    y: 140,
    tablePrice: 1500,
  },
  {
    tableNumber: 11,
    tableType: "rectangle",
    numberOfChairs: 16,
    status: "Available",
    x: 510,
    y: 140,
    tablePrice: 1500,
  },
  {
    tableNumber: 12,
    tableType: "rectangle",
    numberOfChairs: 16,
    status: "Seated",
    x: 260,
    y: 300,
    tablePrice: 1500,
  },
  {
    tableNumber: 13,
    tableType: "rectangle",
    numberOfChairs: 16,
    status: "Available",
    x: 510,
    y: 300,
    tablePrice: 1500,
  },
  {
    tableNumber: 14,
    tableType: "roundMedium",
    numberOfChairs: 4,
    status: "Available",
    x: 750,
    y: 170,
    tablePrice: 450,
  },
  {
    tableNumber: 15,
    tableType: "roundMedium",
    numberOfChairs: 4,
    status: "Seated",
    x: 750,
    y: 280,
    tablePrice: 450,
  },
  {
    tableNumber: 16,
    tableType: "roundMedium",
    numberOfChairs: 4,
    status: "Seated",
    x: 750,
    y: 400,
    tablePrice: 450,
  },

  {
    tableNumber: 17,
    tableType: "roundBig",
    numberOfChairs: 4,
    status: "Available",
    x: 990,
    y: 200,
    tablePrice: 500,
  },
  {
    tableNumber: 18,
    tableType: "roundBig",
    numberOfChairs: 4,
    status: "Available",
    x: 990,
    y: 355,
    tablePrice: 500,
  },
  {
    tableNumber: 19,
    tableType: "roundMedium",
    numberOfChairs: 4,
    status: "Available",
    x: 875,
    y: 170,
    tablePrice: 450,
  },
  {
    tableNumber: 20,
    tableType: "roundMedium",
    numberOfChairs: 4,
    status: "Seated",
    x: 875,
    y: 280,
    tablePrice: 450,
  },
  {
    tableNumber: 21,
    tableType: "roundMedium",
    numberOfChairs: 4,
    status: "Seated",
    x: 875,
    y: 400,
    tablePrice: 450,
  },
  {
    tableNumber: 22,
    tableType: "squareBig",
    numberOfChairs: 8,
    status: "Available",
    x: 100,
    y: 500,
    tablePrice: 750,
  },

  {
    tableNumber: 23,
    tableType: "squareMedium",
    numberOfChairs: 6,
    status: "Seated",
    x: 260,
    y: 490,
    tablePrice: 350,
  },
  {
    tableNumber: 24,
    tableType: "squareMedium",
    numberOfChairs: 6,
    status: "Seated",
    x: 260,
    y: 570,
    tablePrice: 350,
  },
  {
    tableNumber: 25,
    tableType: "squareMedium",
    numberOfChairs: 6,
    status: "Seated",
    x: 370,
    y: 490,
    tablePrice: 350,
  },
  {
    tableNumber: 26,
    tableType: "squareMedium",
    numberOfChairs: 6,
    status: "Seated",
    x: 370,
    y: 570,
    tablePrice: 350,
  },

  {
    tableNumber: 27,
    tableType: "squareMedium",
    numberOfChairs: 6,
    status: "Seated",
    x: 480,
    y: 490,
    tablePrice: 350,
  },
  {
    tableNumber: 28,
    tableType: "squareMedium",
    numberOfChairs: 48,
    status: "Seated",
    x: 480,
    y: 570,
    tablePrice: 350,
  },
  {
    tableNumber: 29,
    tableType: "squareMedium",
    numberOfChairs: 6,
    status: "Seated",
    x: 590,
    y: 490,
    tablePrice: 350,
  },
  {
    tableNumber: 30,
    tableType: "squareMedium",
    numberOfChairs: 6,
    status: "Seated",
    x: 590,
    y: 570,
    tablePrice: 350,
  },
  {
    tableNumber: 31,
    tableType: "squareMedium",
    numberOfChairs: 6,
    status: "Seated",
    x: 700,
    y: 490,
    tablePrice: 350,
  },
  {
    tableNumber: 32,
    tableType: "squareMedium",
    numberOfChairs: 6,
    status: "Seated",
    x: 700,
    y: 570,
    tablePrice: 350,
  },
  {
    tableNumber: 33,
    tableType: "roundBig",
    numberOfChairs: 6,
    status: "Seated",
    x: 810,
    y: 510,
    tablePrice: 500,
  },
  {
    tableNumber: 34,
    tableType: "squareBig",
    numberOfChairs: 8,
    status: "Available",
    x: 970,
    y: 500,
    tablePrice: 750,
  },
];
