export const tables = [
  { id: 1, type: "squareBig", chairs: 8, status: "Available", x: 100, y: 50 },
  { id: 2, type: "roundSmall", chairs: 2, status: "Pending", x: 280, y: 70 },
  { id: 3, type: "roundBig", chairs: 10, status: "Seated", x: 400, y: 50 },
  { id: 4, type: "roundSmall", chairs: 2, status: "Available", x: 570, y: 70 },
  { id: 5, type: "roundSmall", chairs: 2, status: "Seated", x: 680, y: 70 },
  { id: 6, type: "roundBig", chairs: 10, status: "Available", x: 800, y: 50 },
  { id: 7, type: "squareBig", chairs: 8, status: "Seated", x: 980, y: 50 },
  {
    id: 8,
    type: "roundMedium",
    chairs: 4,
    status: "Available",
    x: 50,
    y: 170,
  },
  {
    id: 9,
    type: "roundMedium",
    chairs: 4,
    status: "Pending",
    x: 50,
    y: 300,
  },
  { id: 10, type: "rectangle", chairs: 16, status: "Seated", x: 210, y: 180 },
  {
    id: 11,
    type: "rectangle",
    chairs: 16,
    status: "Available",
    x: 530,
    y: 180,
  },
  {
    id: 11,
    type: "roundMedium",
    chairs: 4,
    status: "Available",
    x: 840,
    y: 170,
  },
  {
    id: 12,
    type: "roundMedium",
    chairs: 4,
    status: "Pending",
    x: 840,
    y: 300,
  },
  {
    id: 13,
    type: "roundMedium",
    chairs: 4,
    status: "Available",
    x: 970,
    y: 170,
  },
  {
    id: 14,
    type: "roundMedium",
    chairs: 4,
    status: "Pending",
    x: 970,
    y: 300,
  },
  { id: 15, type: "squareBig", chairs: 8, status: "Available", x: 100, y: 500 },

  { id: 16, type: "squareMedium", chairs: 6, status: "Seated", x: 290, y: 450 },
  { id: 17, type: "squareMedium", chairs: 6, status: "Seated", x: 290, y: 560 },
  { id: 18, type: "squareMedium", chairs: 6, status: "Seated", x: 410, y: 450 },
  { id: 19, type: "squareMedium", chairs: 6, status: "Seated", x: 410, y: 560 },
  { id: 20, type: "squareMedium", chairs: 6, status: "Seated", x: 530, y: 450 },
  { id: 21, type: "squareMedium", chairs: 6, status: "Seated", x: 530, y: 560 },
  { id: 22, type: "squareMedium", chairs: 6, status: "Seated", x: 650, y: 450 },
  { id: 23, type: "squareMedium", chairs: 6, status: "Seated", x: 650, y: 560 },
  { id: 24, type: "squareMedium", chairs: 6, status: "Seated", x: 770, y: 450 },
  { id: 25, type: "squareMedium", chairs: 6, status: "Seated", x: 770, y: 560 },
  { id: 26, type: "squareMedium", chairs: 6, status: "Seated", x: 870, y: 510 },
  { id: 27, type: "squareBig", chairs: 8, status: "Available", x: 970, y: 500 },
];
